#!/usr/bin/env bash
source "$(dirname "$0")/lib/common.sh"

require_root_dir
_arrow "Fixing file ownership in sources/..."
sudo chown -R 1000:1000 "${SOURCE_DIR}/"* || _die "Cannot fix ownership (do you have sudo?)"
_success "File ownership fixed"
